---
 - include_vars: "{{ item }}"
   with_first_found:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"

 - include: install.yml
 - include: config.yml
 - include: root-password.yml

